version: '3.8'
services:
  jenkinsci:
    image: jenkins-plugin-dev
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        BASE_IMAGE:
        M2_BIN:
        USER_CI:
        USER_UID: ${LOCAL_UID}
        USER_GID: ${LOCAL_GID}
    environment:
      JENKINS_CI_REPO:
    volumes:
      - ../..:/workspaces:cached
      # vscode customization persistance
      # - ../.vscode-server:/home/${USER_CI}/.vscode-server:cached
    
    command: sleep infinity